name: Update

on:
  workflow_dispatch:
  schedule:
    # “At 00:00 on Friday.” https://crontab.guru/#0_0_*_*_5
    - cron: "0 0 * * 5"

jobs:
  update:
    permissions:
      pull-requests: write
      contents: write
    if: github.event_name != 'schedule' || github.repository == 'prettier/html-ua-styles'
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: yarn

      - name: Update Data
        run: yarn build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update data
          branch: automated-update
          branch-suffix: timestamp
          title: Update data
